global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'currency-exchange'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'currency-conversion'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8081']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8765']

  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8761']


# Run using
# ./prometheus --config.file=path/to/prometheus.yml

# Start grafana using
# bin/grafana-server

# Paste this onto prometheus and execute 
# http_server_requests_seconds_count

